{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fractal-lba.fullname" . }}-backend
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fractal-lba.selectorLabels" . | nindent 6 }}
      app: backend
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
