{{- if .Values.signing.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fractal-lba.fullname" . }}-signing
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.signing.alg "hmac" }}
  hmacKey: {{ .Values.signing.hmacKey | quote }}
  {{- else if eq .Values.signing.alg "ed25519" }}
  ed25519PubB64: {{ .Values.signing.ed25519PubB64 | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.metricsBasicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fractal-lba.fullname" . }}-metrics
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.metricsBasicAuth.password | quote }}
{{- end }}
