apiVersion: v1
kind: Service
metadata:
  name: {{ include "fractal-lba.fullname" . }}-backend
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fractal-lba.selectorLabels" . | nindent 4 }}
    app: backend
