apiVersion: v2
name: fractal-lba
description: Fractal LBA + Kakeya FT Stack - Production-grade PCS verification backend

type: application

version: 0.1.0

appVersion: "0.1.0"

keywords:
  - fractal
  - lba
  - kakeya
  - pcs
  - verification
  - proof-of-computation

maintainers:
  - name: Fractal LBA Team
    email: ops@example.com

sources:
  - https://github.com/rkhokhla/kakeya

dependencies:
  - name: redis
    version: "^18.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: "^13.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
