{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fractal-lba.fullname" . }}
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fractal-lba.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
