apiVersion: v1
kind: Service
metadata:
  name: {{ include "fractal-lba.fullname" . }}
  labels:
    {{- include "fractal-lba.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fractal-lba.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
