name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Phase 11 WP5: Python linting
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          pip install ruff mypy

      - name: Run ruff
        run: |
          ruff check agent/ tests/ || echo "Ruff checks completed with warnings"

      - name: Run mypy
        run: |
          mypy agent/ --ignore-missing-imports || echo "MyPy checks completed with warnings"

  # Phase 1 unit tests (Python)
  unit-tests-python:
    runs-on: ubuntu-latest
    needs: [lint-python]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest numpy

      - name: Run unit tests
        run: |
          python -m pytest tests/test_signals.py tests/test_signing.py -v

  # Phase 11 WP5: Go linting and security
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: ./backend

      - name: Run go vet
        working-directory: ./backend
        run: go vet ./...

      - name: Run gosec
        working-directory: ./backend
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -quiet ./... || echo "Gosec checks completed with warnings"

  # Go backend build and test
  build-go:
    runs-on: ubuntu-latest
    needs: [lint-go]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build backend
        working-directory: ./backend
        run: go build ./...

      - name: Run Go tests
        working-directory: ./backend
        run: go test ./... -v

  # E2E integration tests (Phase 2)
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests-python, build-go]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install pytest numpy requests

      - name: Start backend with Docker Compose
        run: |
          docker-compose -f infra/compose-tests.yml up -d
          sleep 10  # Wait for services to start

      - name: Wait for backend health
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/health; then
              echo "Backend is healthy"
              exit 0
            fi
            echo "Waiting for backend... ($i/30)"
            sleep 2
          done
          echo "Backend failed to become healthy"
          exit 1

      - name: Run E2E tests
        env:
          BACKEND_URL: http://localhost:8080
        run: |
          python -m pytest tests/e2e/ -v

      - name: Collect logs
        if: always()
        run: |
          docker-compose -f infra/compose-tests.yml logs > e2e-logs.txt

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: e2e-logs.txt

      - name: Stop services
        if: always()
        run: |
          docker-compose -f infra/compose-tests.yml down -v

  # Helm lint and validation
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Lint Helm chart
        run: |
          helm lint helm/fractal-lba || echo "Helm chart not yet created (Phase 2 WP4)"

  # Phase 11 WP5: Security scanning with Trivy
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run secret scanner
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD

      - name: Check for plaintext secrets
        run: |
          if grep -r "PCS_HMAC_KEY.*=.*['\"].*['\"]" --exclude-dir=.git --exclude-dir=docs --exclude="*.md" .; then
            echo "ERROR: Found plaintext HMAC keys in code"
            exit 1
          fi
          echo "No plaintext secrets found"
